import torch
import torch.nn as nn
from typing import Optional, Dict, Tuple

from s9.base import FPDTypeIdx, get_float_dtype
from .base import AdapterHubBase, ModuleAdapterBase
from framesmoothie.fmlm import FMLMGateGenerator


def _corrcoef(a: torch.Tensor, b: torch.Tensor, eps: float = 1e-6) -> torch.Tensor:
    # a,b: [B,D]
    am = a - a.mean(dim=-1, keepdim=True)
    bm = b - b.mean(dim=-1, keepdim=True)
    cov = (am * bm).mean(dim=-1)
    std = (am.square().mean(dim=-1).sqrt() * bm.square().mean(dim=-1).sqrt()).clamp_min(eps)
    return (cov / std).mean()  # scalar


class LRCAHub(AdapterHubBase):
    """
    LRCA context hub with:
      - global shared gate (cross-task): g_global(ctx)
      - per-task local shared gate: g_task(ctx)

    Effective shared gate for a task:
        g_shared(task) = g_global ⊙ g_task

    Gates are generated by FMLM-style rank-R interaction (general-f stable Rank-R factorized FMLM),
    then squashed by sigmoid -> (0,1).
    """
    def __init__(
        self,
        ctx_dim: int,
        rank_shared: int,
        *,
        tasks: Tuple[str, ...] = ("semantic", "instance"),
        task_id_dim: int = 1,
        fmlm_rank: int = 8,
        fmlm_eta: float = 0.1,
        dtype_idx: FPDTypeIdx = 64,
    ):
        super().__init__()
        self.dtype = get_float_dtype(dtype_idx)
        self.ctx_dim = int(ctx_dim)
        self.rank_shared = int(rank_shared)
        self.tasks = tuple(tasks)
        self.task_id_dim = int(task_id_dim)
        self._task_to_id = {t: i for i, t in enumerate(self.tasks)}

        self.g_global_gen = FMLMGateGenerator(
            gate_dim=self.rank_shared,
            cond_dims=[self.ctx_dim],
            rank=fmlm_rank,
            eta=fmlm_eta,
            dtype_idx=dtype_idx,
        )
        self.g_task_gen = nn.ModuleDict({
            t: FMLMGateGenerator(
                gate_dim=self.rank_shared,
                cond_dims=[self.ctx_dim + self.task_id_dim],
                rank=fmlm_rank,
                eta=fmlm_eta,
                dtype_idx=dtype_idx,
            )
            for t in self.tasks
        })

        self._ctx: Optional[torch.Tensor] = None
        self._cache_global: Optional[torch.Tensor] = None
        self._cache_task: Dict[str, torch.Tensor] = {}
        self._cache_shared: Dict[str, torch.Tensor] = {}

        # diagnostics (scalars)
        self._diag: Dict[str, torch.Tensor] = {}

    def set_context(self, ctx: torch.Tensor) -> None:
        self._ctx = ctx.to(dtype=self.dtype)
        self._cache_global = None
        self._cache_task.clear()
        self._cache_shared.clear()
        self._diag.clear()

    def clear(self) -> None:
        self._ctx = None
        self._cache_global = None
        self._cache_task.clear()
        self._cache_shared.clear()
        self._diag.clear()

    def get_context(self) -> Optional[torch.Tensor]:
        return self._ctx
def get_task_context(self, task: str) -> torch.Tensor:
    if self._ctx is None:
        raise RuntimeError("LRCAHub context is not set")
    if task not in self._task_to_id:
        raise KeyError(f"Unknown task: {task}")
    B = self._ctx.shape[0]
    if self.task_id_dim == 1:
        tid = torch.full((B, 1), float(self._task_to_id[task]), dtype=self._ctx.dtype, device=self._ctx.device)
    else:
        # one-hot encoding; require task_id_dim == len(tasks) for consistency
        tid = torch.zeros((B, self.task_id_dim), dtype=self._ctx.dtype, device=self._ctx.device)
        idx = self._task_to_id[task]
        if idx >= self.task_id_dim:
            raise ValueError("task_id_dim is too small for one-hot task encoding")
        tid[:, idx] = 1.0
    return torch.cat([self._ctx, tid], dim=-1)


    def global_gate(self) -> torch.Tensor:
        if self._ctx is None:
            raise RuntimeError("LRCAHub context is not set")
        if self._cache_global is None:
            self._cache_global = self.g_global_gen([self._ctx])
        return self._cache_global

    def task_gate(self, task: str) -> torch.Tensor:
        if self._ctx is None:
            raise RuntimeError("LRCAHub context is not set")
        if task not in self.g_task_gen:
            raise KeyError(f"Unknown task: {task}")
        if task not in self._cache_task:
            ctx_t = self.get_task_context(task)
            self._cache_task[task] = self.g_task_gen[task]([ctx_t])
        return self._cache_task[task]

    def shared_gate(self, task: Optional[str] = None) -> torch.Tensor:
        g_g = self.global_gate()
        if task is None:
            return g_g
        if task in self._cache_shared:
            return self._cache_shared[task]
        g_t = self.task_gate(task)
        g = g_g * g_t
        self._cache_shared[task] = g
        return g

    def get_diagnostics(self) -> dict:
        # compute and cache scalar diagnostics
        if self._ctx is None:
            return {}

        if "g_global_var" not in self._diag:
            g_g = self.global_gate()
            self._diag["g_global_mean"] = g_g.mean()
            self._diag["g_global_var"] = g_g.var(dim=-1).mean()

        # task gates
        for t in self.tasks:
            key_m = f"g_{t}_mean"
            key_v = f"g_{t}_var"
            if key_v not in self._diag:
                g_t = self.shared_gate(t)
                self._diag[key_m] = g_t.mean()
                self._diag[key_v] = g_t.var(dim=-1).mean()

        # correlations (only if both tasks exist)
        if "semantic" in self.tasks and "instance" in self.tasks and "corr_sem_inst" not in self._diag:
            g_sem = self.shared_gate("semantic")
            g_ins = self.shared_gate("instance")
            self._diag["corr_sem_inst"] = _corrcoef(g_sem, g_ins)
            self._diag["corr_global_sem"] = _corrcoef(self.global_gate(), g_sem)
            self._diag["corr_global_inst"] = _corrcoef(self.global_gate(), g_ins)

        # return python numbers + tensors
        return {k: v.detach() for k, v in self._diag.items()}


class LRCALinear(nn.Module):
    """Linear with LRCA (task-shared gate + layer-private gate)."""
    def __init__(
        self,
        base: nn.Linear,
        hub: LRCAHub,
        *,
        task: Optional[str],
        rank_shared: int,
        rank_private: int,
        scale: float = 1.0,
        freeze_base: bool = True,
        dtype_idx: FPDTypeIdx = 64,
        fmlm_rank: int = 8,
        fmlm_eta: float = 0.1,
    ):
        super().__init__()
        self.base = base
        self.hub = hub
        self.task = task
        self.rank_shared = int(rank_shared)
        self.rank_private = int(rank_private)
        self.scale = float(scale)
        self.freeze_base = bool(freeze_base)
        self.dtype = get_float_dtype(dtype_idx)

        in_f = base.in_features
        out_f = base.out_features

        # shared factors
        self.Us = nn.Parameter(torch.randn(out_f, self.rank_shared, dtype=self.dtype) * 0.02)
        self.Vs = nn.Parameter(torch.randn(self.rank_shared, in_f, dtype=self.dtype) * 0.02)

        # private factors
        self.Up = nn.Parameter(torch.randn(out_f, self.rank_private, dtype=self.dtype) * 0.02)
        self.Vp = nn.Parameter(torch.randn(self.rank_private, in_f, dtype=self.dtype) * 0.02)

        # private gate generator (per-layer)
        self.g_private_gen = FMLMGateGenerator(
            gate_dim=self.rank_private,
            cond_dims=[hub.ctx_dim + hub.task_id_dim],
            rank=fmlm_rank,
            eta=fmlm_eta,
            dtype_idx=dtype_idx,
        )

        if self.freeze_base:
            for p in self.base.parameters():
                p.requires_grad_(False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        y0 = self.base(x)
        ctx_base = self.hub.get_context()
        if ctx_base is None:
            raise RuntimeError("LRCAHub context is not set")

        # gates
        g_s = self.hub.shared_gate(self.task)  # [B,Rs] or global if task None
        if self.task is None:
            ctx_p = torch.cat([ctx_base, torch.zeros((ctx_base.shape[0], self.hub.task_id_dim), dtype=ctx_base.dtype, device=ctx_base.device)], dim=-1)
        else:
            ctx_p = self.hub.get_task_context(self.task)
        g_p = self.g_private_gen([ctx_p])        # [B,Rp]

        # delta W x : compute (Us diag(g) Vs) x efficiently
        # x: [..., in_f] -> flatten batch dims to [B*, in_f] but gates are [B, R]
        # We'll assume leading batch dim is B and x is [B,...,in_f]. Use broadcasting over trailing dims.
        B = x.shape[0]
        x2 = x.reshape(B, -1, x.shape[-1])  # [B,*,in_f]
        # shared
        xs = torch.matmul(x2, self.Vs.t())              # [B,*,Rs]
        xs = xs * g_s.unsqueeze(1)                      # [B,*,Rs]
        ds = torch.matmul(xs, self.Us.t())              # [B,*,out_f]
        # private
        xp = torch.matmul(x2, self.Vp.t())              # [B,*,Rp]
        xp = xp * g_p.unsqueeze(1)                      # [B,*,Rp]
        dp = torch.matmul(xp, self.Up.t())              # [B,*,out_f]

        delta = (ds + dp) * self.scale
        delta = delta.reshape(*x.shape[:-1], self.base.out_features)
        return y0 + delta


class LRCAAdapter(ModuleAdapterBase):
    """Swappable LRCA adapter plugin."""
    def __init__(
        self,
        *,
        ctx_dim: int,
        rank_shared: int = 8,
        rank_private: int = 4,
        tasks: Tuple[str, ...] = ("semantic", "instance"),
        task_id_dim: int = 1,
        fmlm_rank: int = 8,
        fmlm_eta: float = 0.1,
        dtype_idx: FPDTypeIdx = 64,
        scale: float = 1.0,
        freeze_base: bool = True,
    ):
        super().__init__()
        self.ctx_dim = int(ctx_dim)
        self.rank_shared = int(rank_shared)
        self.rank_private = int(rank_private)
        self.tasks = tuple(tasks)
        self.fmlm_rank = int(fmlm_rank)
        self.fmlm_eta = float(fmlm_eta)
        self.dtype_idx = dtype_idx
        self.scale = float(scale)
        self.freeze_base = bool(freeze_base)

        self.hub = LRCAHub(
            ctx_dim=self.ctx_dim,
            rank_shared=self.rank_shared,
            tasks=self.tasks,
            task_id_dim=self.task_id_dim,
            fmlm_rank=self.fmlm_rank,
            fmlm_eta=self.fmlm_eta,
            dtype_idx=dtype_idx,
        )

    def set_context(self, ctx: torch.Tensor) -> None:
        self.hub.set_context(ctx)

    def clear(self) -> None:
        self.hub.clear()

    def wrap_linear(self, base: nn.Linear, *, task: Optional[str] = None) -> nn.Module:
        return LRCALinear(
            base=base,
            hub=self.hub,
            task=task,
            rank_shared=self.rank_shared,
            rank_private=self.rank_private,
            scale=self.scale,
            freeze_base=self.freeze_base,
            dtype_idx=self.dtype_idx,
            fmlm_rank=self.fmlm_rank,
            fmlm_eta=self.fmlm_eta,
        )
